name: claymodel
channels:
  - conda-forge
  - nvidia
  - pytorch
dependencies:
  - python=3.11
  - pip
  - pip:
    - --extra-index-url https://download.pytorch.org/whl/cu121
    - torch==2.4.0+cu121
    - torchvision==0.19.0+cu121
    - einops~=0.7.0
    - geopandas
    - jsonargparse[signatures]>=4.27.7
    - lightning==2.4.0
    - matplotlib
    - python-box
    - s2cloudless
    - scikit-image
    - scikit-learn
    - timm
    - vit-pytorch
    - wandb
